### PR TITLE
Unleash the power of Block Directive

### PR DESCRIPTION
**Pull request by LiYanan2004**
## Modifications

- Unleash the full power for users to customize their own view instead of using MarkdownView
- Update APIs
- Re-structure related files

## Custom View inside MarkdownView

Now, BlockDirectiveDisplayable gives you text from the body of block directives.

You can add custom view inside MarkdownView by implementing `BlockDirectiveDisplayable`.

### Example

If you want to support LateX in your app along with MarkdownView.

Define your provider:

```swift
import LaTeXSwiftUI // https://github.com/colinc86/LaTeXSwiftUI

struct LatexProvider: BlockDirectiveDisplayable {
    func makeView(arguments: [BlockDirectiveArgument], text: String) -> some View {
        LaTeX(text).id(text)
    }
}

extension BlockDirectiveDisplayable where Self == LatexProvider {
    static var latex: LatexProvider { .init() }
}
```

Then, adding it to MarkdownView:

```swift
MarkdownView(...)
    .blockDirectiveProvider(.latex, for: "latex")
```

🎉 That’s it. Now if you write markdown like this:

```markdown
# LateX

@latex { Euler's identity is $e^{i\\pi}+1=0$. }
```

You can see this:

latex

## Deprecations

The required function `makeView(arguments:innerView:)` has been replaced with `makeView(arguments:text:)`

> Tips: If your custom view depends on previous `innerView`, you can replace it with `MarkdownView(text: text)`

### CODE REVIEW

**Comment by LiYanan2004** [comment]
This enhancement may satisfy the feature request: #19

**Comment by hugo53** [comment]
@LiYanan2004 Thank you for your always great work. It works fine on my side. However, it seems `@latex` is a must in input string. Could you please share how can we go without that annotation? I think in most of Latex texts, there is no `@latex` annotation.

**Comment by LiYanan2004** [comment]
@hugo53 You’re right. 

I mean you can now **add LateXView as a part of MarkdownView**. If you’re working on views with static markdown text, you can simply do that. If you are developing document editors, you can try to manually detect this syntax(use the dependency of LateXSwiftUI package) and dynamically wrap it using `@latex` annotation.

To sum up, It’s full of potential 😁

**Comment by hugo53** [comment]
Yes I'm thinking about that as we may need to do preprocessing text in that case. 
I have found another case, although it is rare, where LaTeX does not work if the text has both a code block and LaTeX text. Please check below image.
Screenshot 2023-08-05 at 15 38 41

**Comment by LiYanan2004** [comment]
@hugo53 Congratulation. You found a bug of swift-markdown.🤣 This bug only occurs when the code block is the first Markdown item. I will report this bug.

**Comment by hugo53** [comment]
@LiYanan2004 Ah correct, I added some words at first and it works fine now. Weird bug 🤣

**Comment by LiYanan2004** [comment]
@hugo53 Based on the documentation, you can extract ranges that contains LateX Syntax using this method:

```swift
func findLateXRanges(in text: String) -> [Range<String.Index>] {
    let singleDollarPattern = #"\$((?!\$).)+\$"#
    let doubleDollarPattern = #"\$\$(.+)\$\$"#
    let squareBracketsPattern = #"\\\[(.+)\\\]"#
    let beginEndPattern = #"\\begin{equation}(.+)\\end{equation}"#
    let beginEndWithAsteriskPattern = #"\\begin{equation*}(.+)\\end{equation*}"#
    let pattern = try! Regex("\(doubleDollarPattern)|\(singleDollarPattern)|\(squareBracketsPattern)|\(beginEndPattern)|\(beginEndWithAsteriskPattern)")
    return text.matches(of: pattern).map { $0.range }
}
```

**Comment by hugo53** [comment]
@LiYanan2004 Thank you for suggestion. I will check more on that!

**Pull request merged**
