### PR TITLE
Adding voice over support for headings

### PR DESCRIPTION
**Pull request by manikantasanisetty**
Adding voice-over support for markdown.

https://github.com/user-attachments/assets/0d365ad5-a4cf-4410-8d69-06c018a29712

### CODE REVIEW

**Comment by manikantasanisetty** [comment]
@LiYanan2004 Please reivew the PR

**Comment by LiYanan2004** [comment]
Linked issue: #28

**Comment by LiYanan2004** [comment]
Sorry for late reply. I’ll review it later today! @manikantasanisetty

**Review by LiYanan2004 — APPROVED** [review]

**Comment by LiYanan2004** [comment]
@manikantasanisetty Great work. Thank you!

**Comment by manikantasanisetty** [comment]
@LiYanan2004  Can you publish a new release with latest changes?

**Comment by LiYanan2004** [comment]
Sure, will release it tomorrow

**Comment by LiYanan2004** [comment]
@manikantasanisetty Published

**Pull request merged**
